{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pehelypress.databaseSecret" . }}
  labels:
    {{- include "pehelypress.labels" . | nindent 4 }}
type: Opaque
data:
  PASSWORD: {{ randAlphaNum 23 | b64enc | quote }}
{{- end }}
