{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pehelypress.databaseSecret" . }}
  labels:
    {{- include "pehelypress.labels" . | nindent 4 }}
type: Opaque
data:
  USERNAME: {{ .Values.username | b64enc | quote }}
  PASSWORD: {{ .Values.password | b64enc | quote }}
  DATABASE: {{ .Values.database | b64enc | quote }}
  HOSTNAME: {{ .Values.hostname | b64enc | quote }}
{{- end }}
